apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: gandalf-monitor
  namespace: monitoring
  labels:
    app: gandalf-web
spec:
  namespaceSelector:
    matchNames:
      - default
  selector:
    matchLabels:
      app: gandalf-web
  endpoints:
    - port: http
      path: /metrics
      interval: 15s
