apiVersion: apps/v1
kind: Deployment
metadata:
  name: gandalf-web-server
  labels:
    app: gandalf-web-server
spec:
  replicas: 1
  selector:
    matchLabels:
      app: gandalf-web-server
  template:
    metadata:
      labels:
        app: gandalf-web-server
    spec:
      containers:
      - name: gandalf-web-server
        image: your-docker-image:latest
        ports:
        - containerPort: 80
        resources:
          requests:
            memory: "128Mi"
            cpu: "500m"
          limits:
            memory: "256Mi"
            cpu: "1"
        readinessProbe:
          httpGet:
            path: /
            port: 80
          initialDelaySeconds: 5
          periodSeconds: 10
        livenessProbe:
          httpGet:
            path: /
            port: 80
          initialDelaySeconds: 15
          periodSeconds: 20