apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "gandalf-chart.fullname" . }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels: {{- include "gandalf-chart.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels: {{- include "gandalf-chart.selectorLabels" . | nindent 8 }}
    spec:
      securityContext:
        runAsNonRoot: true
        runAsUser: 1000
      containers:
      - name: web
        image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
        ports:
        - containerPort: 80
        resources: {{- toYaml .Values.resources | nindent 10 }}
