apiVersion: v1
kind: Service
metadata:
  name: {{ include "gandalf-chart.fullname" . }}
  labels: {{- include "gandalf-chart.selectorLabels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
  - name: http
    port: 80
    targetPort: 80
  selector: {{- include "gandalf-chart.selectorLabels" . | nindent 4 }}
