name: Build & Release Gandalf Web

on:
  push:
    tags: ["v*"]          # only when you push a tag
  workflow_dispatch:      # allow manual runs

env:
  IMAGE_NAME: ghcr.io/${{ github.repository }}/gandalf-web

jobs:
  build-push:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write         # needed for ghcr push
    steps:
    - uses: actions/checkout@v4

    # Set up Docker buildx
    - uses: docker/setup-buildx-action@v3

    # Log in to GHCR
    - uses: docker/login-action@v3
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.CR_PAT }}

    # Build & push image
    - name: Build and push
      uses: docker/build-push-action@v5
      with:
        push: true
        tags: |
          ${{ env.IMAGE_NAME }}:${{ github.ref_name }}   # e.g. v0.4
          ${{ env.IMAGE_NAME }}:latest

  helm-package:
    runs-on: ubuntu-latest
    needs: build-push
    steps:
    - uses: actions/checkout@v4

    # Package chart (helm lint already green)
    - name: Package Helm chart
      run: |
        helm dependency update gandalf-chart
        helm package gandalf-chart --app-version ${{ github.ref_name }} \
                                   --version ${{ github.ref_name }}

    # Upload chart as artifact
    - uses: actions/upload-artifact@v4
      with:
        name: gandalf-chart
        path: "*.tgz"

  # OPTIONAL – create a GitHub release and attach chart
  release:
    runs-on: ubuntu-latest
    needs: helm-package
    permissions:
      contents: write
    steps:
    - uses: softprops/action-gh-release@v2
      with:
        tag_name: ${{ github.ref_name }}
        files: "*.tgz"
