name: Build & Release Gandalf Web

on:
  push:
    tags:
      - "v*"
  workflow_dispatch:

env:
  # Docker Hub image path:  docker.io/<username>/<repo>:tag
  IMAGE: docker.io/${{ secrets.DOCKERHUB_USERNAME }}/gandalf-web


jobs:
  build-and-push:
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
      - uses: actions/checkout@v4
      - uses: docker/setup-buildx-action@v3
      - uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Build and push
        uses: docker/build-push-action@v5
        with:
          push: true
          tags: |
            ${{ env.IMAGE }}:${{ github.ref_name }}
            ${{ env.IMAGE }}:latest

  helm-package:
    runs-on: ubuntu-latest
    needs: build-and-push
    steps:
      - uses: actions/checkout@v4
      - name: Package Helm chart
        run: |
          helm dependency update gandalf-chart
          helm package gandalf-chart --app-version ${{ github.ref_name }} \
                                     --version ${{ github.ref_name }}
      - uses: actions/upload-artifact@v4
        with:
          name: gandalf-chart
          path: "*.tgz"

  # OPTIONAL – create a GitHub release and attach chart
  release:
    runs-on: ubuntu-latest
    needs: helm-package
    permissions:
      contents: write
    steps:
      - uses: softprops/action-gh-release@v2
        with:
          tag_name: ${{ github.ref_name }}
          files: "*.tgz"
